# Beyond Data Manipulation

##1. Basic Statistical Testing


*  We use statistics in a lot of different ways in data science, and on this lecture, I want to refresh your knowledge of hypothesis testing, which is a core data analysis activity behind experimentation. The goal of
 hypothesis testing is to determine if, for instance, the two different conditions we have in an experiment 
 have resulted in different impacts

In [ ]:
import numpy as np
import pandas as pd

# Now let's bring in some new libraries from scipy
from scipy import stats

* scipy is an interesting collection of libraries for data science and you'll use most or perpahs all of
 these libraries. It includes numpy and pandas, but also plotting libraries such as matplotlib, and a number of scientific library functions as well.
* When we do hypothesis testing, we actually have two statements of interest: 
 1. the first is our actual explanation, which we call the alternative hypothesis.
 2. the second is that the explanation we have is not sufficient, and we call this the null hypothesis.
* Our actual testing method is to determine whether the null hypothesis is true or not. If we find that there is a difference between groups, then we can reject the null
 hypothesis and we accept our alternative.

In [ ]:
df=pd.read_csv ('/content/drive/MyDrive/etc/grades.csv')
df.head()

                             student_id  ...         assignment6_submission
0  B73F2C11-70F0-E37D-8B10-1D20AFED50B1  ...  2015-11-22 18:31:15.934000000
1  98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1  ...  2015-12-21 17:07:24.275000000
2  D0F62040-CEB0-904C-F563-2F8620916C4E  ...  2016-01-17 16:24:42.765000000
3  FFDF2B2C-F514-EF7F-6538-A6A53518E9DC  ...  2016-05-26 08:09:12.058000000
4  5ECBEEB6-F1CE-80AE-3164-E45E99473FB4  ...  2016-01-05 01:06:59.546000000

[5 rows x 13 columns]

In [ ]:
print("There are {} rows and {} columns".format(df.shape[0], df.shape[1]))

There are 2315 rows and 13 columns

* Segment this population into two pieces.
1. Those who finish the first assignment by the end of December 2015, we'll call them early finishers, and 
2. those who finish it sometime after that, we'll call them late finishers.

In [ ]:
early_finishers=df[pd.to_datetime(df['assignment1_submission']) < '2016']
early_finishers.head()

                             student_id  ...         assignment6_submission
0  B73F2C11-70F0-E37D-8B10-1D20AFED50B1  ...  2015-11-22 18:31:15.934000000
1  98A0FAE0-A19A-13D2-4BB5-CFBFD94031D1  ...  2015-12-21 17:07:24.275000000
4  5ECBEEB6-F1CE-80AE-3164-E45E99473FB4  ...  2016-01-05 01:06:59.546000000
5  D09000A0-827B-C0FF-3433-BF8FF286E15B  ...  2016-01-20 19:54:46.166000000
8  C9D51293-BD58-F113-4167-A7C0BAFCB6E5  ...  2016-01-19 15:24:31.060000000

[5 rows x 13 columns]

In [ ]:
late_finishers = df[~df.index.isin(early_finishers.index)]
late_finishers.head()

                             student_id  ...         assignment6_submission
2  D0F62040-CEB0-904C-F563-2F8620916C4E  ...  2016-01-17 16:24:42.765000000
3  FFDF2B2C-F514-EF7F-6538-A6A53518E9DC  ...  2016-05-26 08:09:12.058000000
6  3217BE3F-E4B0-C3B6-9F64-462456819CE4  ...  2016-03-23 14:02:00.987000000
7  F1CB5AA1-B3DE-5460-FAFF-BE951FD38B5F  ...  2016-02-18 08:35:04.796000000
9  E2C617C2-4654-622C-AB50-1550C4BE42A0  ...  2016-03-30 20:33:13.554000000

[5 rows x 13 columns]

* Other ways to do this.
1. Copy and paste the first projection and change the sign.
2. Do a join of the dataframe df with early_finishers -  you do a left join you only keep the items in the left dataframe.
3. Make a function that determines if someone is early or late and call apply() and add a new column.

In [ ]:
print(early_finishers['assignment1_grade'].mean())
print(late_finishers['assignment1_grade'].mean())

74.94728457024303
74.0450648477065

* Are they same? or Similar?

1. the alternative hypothesis ("These are different")
2. the null hypothesis ("These are the same")

* When doing hypothesis testing, we have to choose a significance level as a threshold for how much of a chance we're willing to accept. This significance level is typically called alpha.
* For this example, let's use a threshold of 0.05 for our alpha or 5%. Now this is a commonly used number but it's really quite arbitrary.
* The SciPy library contains a number of different statistical tests and forms a basis for hypothesis testing in Python and we're going to use the ttest_ind() function which does an independent t-test (meaning the
populations are not related to one another). The result of ttest_index() are the t-statistic and a p-value.
* It's this latter value, the probability, which is most important to us, as it indicates the chance (between
 0 and 1) of our null hypothesis being True.

In [ ]:
from scipy.stats import ttest_ind

In [ ]:
ttest_ind(early_finishers['assignment1_grade'], late_finishers['assignment1_grade'])

Ttest_indResult(statistic=1.322354085372139, pvalue=0.1861810110171455)

* So here we see that the probability is 0.18, and this is above our alpha value of 0.05. **This means that we
 cannot reject the null hypothesis.**
* The null hypothesis was that the two populations are the same, and we don't have enough certainty in our evidence (because it is greater than alpha) to come to a conclusion to the contrary. This doesn't mean that we have proven the populations are the same.

In [ ]:
# Why don't we check the other assignment grades?
print(ttest_ind(early_finishers['assignment2_grade'], late_finishers['assignment2_grade']))
print(ttest_ind(early_finishers['assignment3_grade'], late_finishers['assignment3_grade']))
print(ttest_ind(early_finishers['assignment4_grade'], late_finishers['assignment4_grade']))
print(ttest_ind(early_finishers['assignment5_grade'], late_finishers['assignment5_grade']))
print(ttest_ind(early_finishers['assignment6_grade'], late_finishers['assignment6_grade']))

Ttest_indResult(statistic=1.2514717608216366, pvalue=0.2108889627004424)
Ttest_indResult(statistic=1.6133726558705392, pvalue=0.10679998102227865)
Ttest_indResult(statistic=0.049671157386456125, pvalue=0.960388729789337)
Ttest_indResult(statistic=-0.05279315545404755, pvalue=0.9579012739746492)
Ttest_indResult(statistic=-0.11609743352612056, pvalue=0.9075854011989656)

* It looks like in this data we do not have enough evidence to suggest the populations differ with respect to grade. 
* Let's take a look at those p-values for a moment though, because they are saying things that can inform experimental design down the road. For instance, one of the assignments, assignment 3, has a p-value around 0.1.
* This means that if we accepted a level of chance similarity of 11% this would have been considered statistically significant. 
* As a research, this would suggest to me that there is something here worth considering following up on. For instance, if we had a small number of participants (we don't) or if there was something unique about this assignment as it relates to our experiment (whatever it was) then there may be followup experiments we could run.

* t 검정 : 집단 간의 차이 비교하는 방법
 * 기본적으로 평균을 비교
 * 집단의 특성에 따라 다른 방법을 적용 (서로 영향을 미치는지, 연관성이 있는지 등)

* p-value 
 * p-value가 작아질수록 가정하는 주장에 대한 신뢰도가 올라가게 됨.
 * ex : 두 집단의 차이가 있다는 주장에서 p-value가 0.05(5%) 이하면 95%로 통계를 신뢰할 수 있기 때문에  두 집단 간의 유의미한 차이가 있는 것이고 0.05 이상이면 통계를 신뢰할 수 없기 때문에 차이가 있지 않다고 해석할 수 있다.

In [ ]:
df1=pd.DataFrame([np.random.random(100) for x in range(100)]) #왜 5줄이지?
df1.head()

         0         1         2   ...        97        98        99
0  0.549431  0.466648  0.356381  ...  0.730386  0.387607  0.767305
1  0.046914  0.758400  0.290741  ...  0.430649  0.785595  0.235482
2  0.101766  0.141578  0.754728  ...  0.376136  0.206680  0.169553
3  0.303889  0.190116  0.021465  ...  0.436856  0.835159  0.976610
4  0.180026  0.634389  0.244286  ...  0.919722  0.785077  0.204839

[5 rows x 100 columns]

In [ ]:
df2=pd.DataFrame([np.random.random(100) for x in range(100)])
df2.head()

         0         1         2   ...        97        98        99
0  0.420026  0.222598  0.071851  ...  0.812352  0.826949  0.113539
1  0.050534  0.266462  0.764995  ...  0.478818  0.761725  0.774049
2  0.718868  0.182131  0.356531  ...  0.851265  0.843380  0.572074
3  0.899137  0.588629  0.938045  ...  0.638682  0.096736  0.687116
4  0.744067  0.603483  0.346595  ...  0.543359  0.019469  0.617147

[5 rows x 100 columns]

In [ ]:
# Are these two DataFrames the same? Maybe a better question is, for a given row inside of df1, is it the same
# as the row inside df2?

# Let's take a look. Let's say our critical value is 0.1, or and alpha of 10%. And we're going to compare each
# column in df1 to the same numbered column in df2. And we'll report when the p-value isn't less than 10%,
# which means that we have sufficient evidence to say that the columns are different.

def test_columns(alpha=0.1):
    num_diff = 0
    for col in df1.columns:
        teststat, pval = ttest_ind(df1[col], df2[col])
        if pval <= alpha:
            print("Col {} is statistically significantly different at alpha={}, pval = {}".format(col, alpha, pval))
            num_diff +=1
    print("Total number different was {}, which is {}%".format(num_diff, float(num_diff)/len(df1.columns)*100))

test_columns()

Col 29 is statistically significantly different at alpha=0.1, pval = 0.012505863697541836
Col 40 is statistically significantly different at alpha=0.1, pval = 0.01504919810509086
Col 50 is statistically significantly different at alpha=0.1, pval = 0.06420231785144473
Col 57 is statistically significantly different at alpha=0.1, pval = 0.06968514752114983
Col 70 is statistically significantly different at alpha=0.1, pval = 0.022607458458111074
Col 75 is statistically significantly different at alpha=0.1, pval = 0.006680066737815461
Col 97 is statistically significantly different at alpha=0.1, pval = 0.07071075147273605
Total number different was 7, which is 7.000000000000001%

In [ ]:
test_columns(0.05)

Col 29 is statistically significantly different at alpha=0.05, pval = 0.012505863697541836
Col 40 is statistically significantly different at alpha=0.05, pval = 0.01504919810509086
Col 70 is statistically significantly different at alpha=0.05, pval = 0.022607458458111074
Col 75 is statistically significantly different at alpha=0.05, pval = 0.006680066737815461
Total number different was 4, which is 4.0%

* What's a reasonable threshold? Depends on your question, and you need to engage domain experts to better understand what they would consider significant.

In [ ]:
df2=pd.DataFrame([np.random.chisquare(df=1,size=100) for x in range(100)])
test_columns()

Col 0 is statistically significantly different at alpha=0.1, pval = 1.5903371863666386e-05
Col 1 is statistically significantly different at alpha=0.1, pval = 0.0005005608991052979
Col 2 is statistically significantly different at alpha=0.1, pval = 0.0018228912905307246
Col 3 is statistically significantly different at alpha=0.1, pval = 0.008946924818852401
Col 4 is statistically significantly different at alpha=0.1, pval = 2.9702453409784508e-05
Col 5 is statistically significantly different at alpha=0.1, pval = 0.000452861238248883
Col 6 is statistically significantly different at alpha=0.1, pval = 0.002491232812070528
Col 7 is statistically significantly different at alpha=0.1, pval = 8.965565064463448e-07
Col 8 is statistically significantly different at alpha=0.1, pval = 0.002970354432730329
Col 9 is statistically significantly different at alpha=0.1, pval = 0.0021076528614830813
Col 10 is statistically significantly different at alpha=0.1, pval = 0.0006640466908666004
Col 11 is statistically significantly different at alpha=0.1, pval = 0.009092877709473054
Col 12 is statistically significantly different at alpha=0.1, pval = 0.008259446254242873
Col 13 is statistically significantly different at alpha=0.1, pval = 7.777572974385219e-07
Col 14 is statistically significantly different at alpha=0.1, pval = 1.900243844031003e-05
Col 15 is statistically significantly different at alpha=0.1, pval = 0.0010426966376527983
Col 16 is statistically significantly different at alpha=0.1, pval = 0.09147463183743108
Col 17 is statistically significantly different at alpha=0.1, pval = 0.00015992029003616772
Col 18 is statistically significantly different at alpha=0.1, pval = 0.0004958931414239214
Col 19 is statistically significantly different at alpha=0.1, pval = 0.0034094924397873225
Col 20 is statistically significantly different at alpha=0.1, pval = 3.913461676879259e-05
Col 21 is statistically significantly different at alpha=0.1, pval = 0.004203529529768502
Col 22 is statistically significantly different at alpha=0.1, pval = 0.0003395580288999778
Col 23 is statistically significantly different at alpha=0.1, pval = 2.2507400075242517e-05
Col 24 is statistically significantly different at alpha=0.1, pval = 3.904338275831377e-05
Col 25 is statistically significantly different at alpha=0.1, pval = 0.0013446359952642298
Col 26 is statistically significantly different at alpha=0.1, pval = 0.00036786022847417536
Col 27 is statistically significantly different at alpha=0.1, pval = 4.199904337621158e-06
Col 28 is statistically significantly different at alpha=0.1, pval = 0.00017655552574834878
Col 29 is statistically significantly different at alpha=0.1, pval = 0.001517953830056869
Col 30 is statistically significantly different at alpha=0.1, pval = 0.003332223463772332
Col 31 is statistically significantly different at alpha=0.1, pval = 0.0012639291649820035
Col 32 is statistically significantly different at alpha=0.1, pval = 0.0084587624655964
Col 33 is statistically significantly different at alpha=0.1, pval = 0.004914858458785786
Col 34 is statistically significantly different at alpha=0.1, pval = 0.00023214608169943335
Col 35 is statistically significantly different at alpha=0.1, pval = 0.0015467889036020882
Col 36 is statistically significantly different at alpha=0.1, pval = 3.9621645593682415e-05
Col 37 is statistically significantly different at alpha=0.1, pval = 0.0030380665670594856
Col 38 is statistically significantly different at alpha=0.1, pval = 0.0002870484561069019
Col 39 is statistically significantly different at alpha=0.1, pval = 0.0002689006046875023
Col 40 is statistically significantly different at alpha=0.1, pval = 0.00781432252791522
Col 41 is statistically significantly different at alpha=0.1, pval = 0.0016198749924970013
Col 42 is statistically significantly different at alpha=0.1, pval = 0.00022914180112434265
Col 43 is statistically significantly different at alpha=0.1, pval = 0.0015145787307284343
Col 44 is statistically significantly different at alpha=0.1, pval = 1.5307240210981715e-05
Col 45 is statistically significantly different at alpha=0.1, pval = 0.011697404400813797
Col 46 is statistically significantly different at alpha=0.1, pval = 2.3777659008216425e-05
Col 47 is statistically significantly different at alpha=0.1, pval = 0.0001218248066410326
Col 48 is statistically significantly different at alpha=0.1, pval = 4.658797256413303e-05
Col 49 is statistically significantly different at alpha=0.1, pval = 0.00035840194741579946
Col 50 is statistically significantly different at alpha=0.1, pval = 0.00039905090587618393
Col 51 is statistically significantly different at alpha=0.1, pval = 0.0010915407235251955
Col 52 is statistically significantly different at alpha=0.1, pval = 0.0006105009259513822
Col 53 is statistically significantly different at alpha=0.1, pval = 0.004081171856270784
Col 54 is statistically significantly different at alpha=0.1, pval = 0.0008180218814887037
Col 55 is statistically significantly different at alpha=0.1, pval = 0.005955375161428287
Col 56 is statistically significantly different at alpha=0.1, pval = 0.0033330129609628035
Col 57 is statistically significantly different at alpha=0.1, pval = 1.6119907845662066e-05
Col 58 is statistically significantly different at alpha=0.1, pval = 0.0009001872176318205
Col 59 is statistically significantly different at alpha=0.1, pval = 0.04892287144883764
Col 60 is statistically significantly different at alpha=0.1, pval = 0.002088581293130928
Col 61 is statistically significantly different at alpha=0.1, pval = 7.320038747756412e-05
Col 62 is statistically significantly different at alpha=0.1, pval = 0.00021062417952936107
Col 63 is statistically significantly different at alpha=0.1, pval = 0.004371682551207994
Col 64 is statistically significantly different at alpha=0.1, pval = 2.8335774161786366e-07
Col 65 is statistically significantly different at alpha=0.1, pval = 0.0010255096162090744
Col 66 is statistically significantly different at alpha=0.1, pval = 0.0016705008423598584
Col 67 is statistically significantly different at alpha=0.1, pval = 0.00014101202700935605
Col 68 is statistically significantly different at alpha=0.1, pval = 0.0008678330108919228
Col 69 is statistically significantly different at alpha=0.1, pval = 0.00011926984716931048
Col 70 is statistically significantly different at alpha=0.1, pval = 6.867915455191792e-07
Col 71 is statistically significantly different at alpha=0.1, pval = 0.00011189665880001197
Col 72 is statistically significantly different at alpha=0.1, pval = 0.0010820785305476737
Col 73 is statistically significantly different at alpha=0.1, pval = 0.048256192274297255
Col 74 is statistically significantly different at alpha=0.1, pval = 0.0033364719395872185
Col 75 is statistically significantly different at alpha=0.1, pval = 0.0024681155626147563
Col 76 is statistically significantly different at alpha=0.1, pval = 0.00011559739513209113
Col 77 is statistically significantly different at alpha=0.1, pval = 0.008933954993814728
Col 78 is statistically significantly different at alpha=0.1, pval = 1.7177138023649464e-06
Col 79 is statistically significantly different at alpha=0.1, pval = 3.7047632774145696e-05
Col 80 is statistically significantly different at alpha=0.1, pval = 0.0023433417672234086
Col 81 is statistically significantly different at alpha=0.1, pval = 0.01985776246395623
Col 82 is statistically significantly different at alpha=0.1, pval = 1.597111027205108e-05
Col 83 is statistically significantly different at alpha=0.1, pval = 0.001167421986642654
Col 84 is statistically significantly different at alpha=0.1, pval = 0.004918285918221603
Col 85 is statistically significantly different at alpha=0.1, pval = 0.0002836731641599846
Col 86 is statistically significantly different at alpha=0.1, pval = 0.0016465198944891684
Col 87 is statistically significantly different at alpha=0.1, pval = 0.0003857689722118148
Col 88 is statistically significantly different at alpha=0.1, pval = 0.0014314136629355618
Col 89 is statistically significantly different at alpha=0.1, pval = 0.0007455197446467161
Col 90 is statistically significantly different at alpha=0.1, pval = 6.280590905630504e-06
Col 91 is statistically significantly different at alpha=0.1, pval = 0.007601605357666276
Col 92 is statistically significantly different at alpha=0.1, pval = 7.373982033523473e-05
Col 93 is statistically significantly different at alpha=0.1, pval = 0.0002567933358199025
Col 94 is statistically significantly different at alpha=0.1, pval = 0.0013630829979633249
Col 95 is statistically significantly different at alpha=0.1, pval = 8.349364319519766e-05
Col 96 is statistically significantly different at alpha=0.1, pval = 8.219576228811479e-05
Col 97 is statistically significantly different at alpha=0.1, pval = 3.1818683514237423e-06
Col 98 is statistically significantly different at alpha=0.1, pval = 0.008391624948185824
Col 99 is statistically significantly different at alpha=0.1, pval = 0.007165318970439677
Total number different was 100, which is 100.0%

## 2. Other Forms of Structured Data
* Nodes (network)
* Tree structure
 * NLP(Language Parse Tree)

## 3. Science isn't broken : p-hacking

[articles]('https://fivethirtyeight.com/features/science-isnt-broken/')

## 4. Goodhart's Law

[Data Skeptice podcast on Goodhart's law](http://dataskeptic.com/epnotes/goodharts-law.php)

## 5. The 5 graph algorithms that you should know

[Medium article](https://towardsdatascience.com/data-scientists-the-five-graph-algorithms-that-you-should-know-30f454fa5513)